### PR TITLE
Fixes to session handling in Ids and Id handling in the Manifest.

### LINKED ISSUE #2313: Cannot deserialize RestaurantsDemo
Steps to repro (hopefully):

1. load `shell_0_6_0/web-shell`
1. type 'restaurants' into search box
1. choose `[demo] find restaurants ...`
1. refresh

image

### PR DESCRIPTION
**Pull request by piotrswigon**
Fixes #2313 - where newly generated session ID have been overwritten by the parsed session, causing ID collisions.

Big TODO Tech Debt Item: Unify ID usage to Id class.

### CODE REVIEW

File: runtime/ts/id.ts [hunk 1]
```diff
@@ -11,7 +11,11 @@
 import {Random} from './random.js';
 
 export class Id {
-  private readonly session: string;
+  // Session at which a logical object (e.g. an Arc) got created.
+  // Part of the stable, permanent ID od this object.
```
Comment (shaper) [inline runtime/ts/id.ts]: od -> of

**Comment by piotrswigon** [comment]
AppVeyor error seems related to Arcs extension (not DevTools), so not related. I'm merging this as it is a pretty fundamental fix.

File: runtime/ts/id.ts (hunk 1 above)
Comment (piotrswigon) [reply runtime/ts/id.ts]: Thanks!
