### PR TITLE
Exposes immediate mode in recipe format and unifies its store instantiation

### LINKED ISSUE #2105: HostedParticleShapes only resolve against context
`hostedParticle` assignments only work if the Particle is defined in the `arc.context` (and not simply inline). Until recently we loaded (almost) all recipes into context by default, masking this issue.

For example, given:

```
import '../List/List.recipes'
import './Playlist.schema'

particle PlaylistItem in 'source/PlaylistItem.js'
  in Playlist playlist
  consume item

recipe PlaylistView
  map #items as items
  create #selected as selected
  ItemMultiplexer
    list = items
    hostedParticle = PlaylistItem
  SelectableItems
    list = items
    selected = selected
```

The system throws like so:

```
Error: Cannot find store manifest:https://$artifacts/Music/Playlist.recipe::0:b42c142249cd1b94df045af5493837c93f2fb2c1:PlaylistItem
    at assert (assert-web.js:11)
    at Arc.instantiate (arc.js:442)
```

If `PlaylistItem` particle is defined in `arc.context` then the `HostedParticleShape` is used from there, and the recipe resolves normally.

### PR DESCRIPTION
**Pull request by piotrswigon**
Introduce `immediateValue` for a recipe handle and uses it for the immediate particle reference.

Design + rationale: https://docs.google.com/document/d/1MvfyJygCv6yc-pegajp1SHDj0e6I2woij04pDxEwFV0/edit#

Some changes:
* Unifies handling of immediate mode in the manifest and in strategies.
* Ensures backing handles are volatile and not serialized.
* Cleans up special handling in the suggestion serialization.

Should fix #2105 and #2274 if we understand them correctly.

### CODE REVIEW

File: runtime/test/arc-tests.js [hunk 1]
```diff
@@ -283,4 +283,40 @@ describe('Arc', function() {
...
+
+    await arc.instantiate(recipe);
+    await arc.idle;
+
+    const serialization = await Manifest.parse(await arc.serialize());
+    assert.isEmpty(serialization.stores, 'Immediate value store should not be serialized');
+    assert.deepEqual(['A', 'B'], serialization.particles.map(p => p.name),
+        'Spec of a particle referenced in an immediate mode should be serialized');
+    assert.deepEqual(['HostedShape'], serialization.shapes.map(s => s.name),
+        'Hosted connection shape should be serialized');
```
Comment (shans) [inline runtime/test/arc-tests.js]: maybe assert something about A.hosts from serialization.recipe too?

File: runtime/ts/recipe/recipe-util.ts [hunk 2]
```diff
@@ -343,6 +353,30 @@ export class RecipeUtil {
     });
   }
 
+  static constructImmediateValueHandle(connection, particleSpec, id) {
```
Comment (shans) [inline runtime/ts/recipe/recipe-util.ts]: Add types for new functions

File: runtime/test/arc-tests.js (hunk 1 above)
Comment (piotrswigon) [reply runtime/test/arc-tests.js]: Good idea, done.

File: runtime/ts/recipe/recipe-util.ts (hunk 2 above)
Comment (piotrswigon) [reply runtime/ts/recipe/recipe-util.ts]: Done.
