### PR TITLE
Fix ID Duplication by adding an optional component to ID generation.

### LINKED ISSUE #758: Assert in Arc test ("deserializing a simple serialized arc produces that arc")
✓ deserializing a simple serialized arc produces that arc (49ms)
(node:23406) AssertionError [ERR_ASSERTION]: false == true
    at ThingMapper.createMappingForThing (file:///Users/mmandlis/arcs/arcs/runtime/api-channel.js:42:5)
    at PECOuterPort.(anonymous function) [as InstantiateParticle] (file:///Users/mmandlis/arcs/arcs/runtime/api-channel.js:240:50)
    at OuterPEC.instantiate (file:///Users/mmandlis/arcs/arcs/runtime/outer-PEC.js:154:19)
    at Arc._instantiateParticle (file:///Users/mmandlis/arcs/arcs/runtime/arc.js:225:14)
    at particles.forEach.recipeParticle (file:///Users/mmandlis/arcs/arcs/runtime/arc.js:349:46)
    at Array.forEach (<anonymous>)
    at Arc.instantiate (file:///Users/mmandlis/arcs/arcs/runtime/arc.js:349:15)
    at <anonymous>
(node:23406) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

### PR DESCRIPTION
**Pull request by shans**
Added await to ensure future exceptions in deserialization are captured and reported.

Fixes #758

### CODE REVIEW

File: runtime/arc.js [hunk 1]
```diff
@@ -227,8 +227,10 @@ ${this.activeRecipe.toString()}`;
     return id;
   }
 
-  generateID() {
-    return `${this.id}:${this._nextLocalID++}`;
+  generateID(component) {
+    if (component == undefined)
+      component = '';
+    return `${this.id}:${component}${this._nextLocalID++}`;
```
Comment (mmandlis) [inline runtime/arc.js]: why would it be duplicate without the component though?

Comment (shans) [reply runtime/arc.js]: Particle IDs aren't serialized or encoded in recipes. So at the moment the count 'restarts' each time an arc is deserialized. This means that particles can alias handle ids.

This is a temporary fix, once we have a proper Runtime object we can design our ID scheme better.
