### PR TITLE
Sheriff Roundup Part 1

### LINKED ISSUE #1490: xen-state.js:120 DOMException: Failed to execute 'start' on 'SpeechRecognition': recognition has already started.

### PR DESCRIPTION
**Pull request by sjmiles**
- better mic handling, fixes #1490
- auto-hide suggestion bar if it pops itself up and is ignored for a few seconds
- avoid trying to instantiate stale suggestions
- move single-use ArcsUtils.methods to where they are used (sorry should have been a separate PR)

### CODE REVIEW

File: shell/app-shell/elements/fb-data/fb-user-context.js [hunk 1]
```diff
@@ -156,10 +156,19 @@ class FbUserContextElement extends Xen.Debug(Xen.Base, log) {
       if (store) {
         // compute description
         const typeName = store.type.toPrettyString().toLowerCase();
-        store.description = ArcsUtils._getHandleDescription(typeName, store.tags, 'my', ownername);
+        store.description = this._getStoreDescription(typeName, store.tags, 'my', ownername);
       }
     }
   }
+  _getStoreDescription(name, tags, user, owner) {
+    let proper = (user === owner) ? 'my' : `${owner}'s`;
```
Comment (shaper) [inline shell/app-shell/elements/fb-data/fb-user-context.js]: Was this something where we thought a feature request for runtime to generate this made sense? I remember us talking about it briefly.

File: shell/app-shell/elements/cloud-data/cloud-handles.js [hunk 2]
```diff
@@ -36,15 +36,29 @@ class CloudHandles extends Xen.Debug(Xen.Base, log) {
...
-  _handleToPath(paths, key, [localHandle, tags]) {
-    if (tags && tags.size > 0 && !tags.has('nosync')) {
-      const contextId = ArcsUtils.getContextHandleId(localHandle.type, tags);
-      const path = `arcs/${key}/${Const.DBLABELS.handles}/${contextId}`;
-      paths[path] = localHandle;
-    }
+  _handleToPaths(paths, key, [localHandle, tags]) {
+    const {type} = localHandle;
+    if (type.isCollection || type.isEntity) {
+      // TODO(sjmiles): the contextId has to be unique for this arc, but also persistent
```
Comment (shaper) [inline shell/app-shell/elements/cloud-data/cloud-handles.js]: Is this something to discuss with runtime team as follow-up?

Comment (sjmiles) [reply shell/app-shell/elements/cloud-data/cloud-handles.js]: I figured not, because this all goes away when we can use Runtime Storage. 

Of course, Storage is blocked on Serialization, which is why I'm a dog with that bone!

File: shell/app-shell/elements/fb-data/fb-user-context.js (hunk 1 above)
Comment (sjmiles) [reply shell/app-shell/elements/fb-data/fb-user-context.js]: Yes, this is absolutely something the runtime needs to do.

Comment (sjmiles) [reply shell/app-shell/elements/fb-data/fb-user-context.js]: https://github.com/PolymerLabs/arcs/issues/1615
