### PR TITLE
Re-build update timing for dom-particle 

### LINKED ISSUE #2945: `startBusy` not working to get async descriptions for Particles (or I'm doing it wrong)
The ArtistFind particle performs a service-query to get information about an artist that can be used for Suggesions. In particular, ArtistFind uses `setParticleDescription` to attach extended information to the `artist` handle.

The service-query is asynchronous and in normal operation, SpecEx kills the Particle before it can `setParticleDescription`. 

I tried adding `startBusy/doneBusy` bookends around the `fetchArtist` method, but it doesn't in practice keep the Particle alive. Logging shows that `startBusy()` is executed, but `doneBusy()` never does (presumably because the worker is dropped).

```
    async fetchArtist(find) {
      this.startBusy();
      try {
        log('startBusy', this.busy);
        const response = await fetch(`${service}&query=${encodeURI(find.name)}`);
        // ... eventually calls setParticleDescription
        log('doneBusy');
      } finally {
        this.doneBusy();
      }
    }
```

Console output:
```
14:12:32.723 ArtistFinder.js:42 ArtistFinder.js startBusy true
14:12:33.051 ArtistFinder.js:42 ArtistFinder.js startBusy true
14:12:33.509 plan-producer.ts:157 PlanProducer [-LdpETFa8FuidC0lHCc5] Produced 17 suggestions [elapsed=1.93s].
```

### PR DESCRIPTION
**Pull request by sjmiles**
Problems addressed:
- Replan timeout was much too long for most cases. 
- dom-particle, like all Particle sub-classes, must bracket asynchrony in `set/doneBusy()` calls so the system can accurately assess idleness.
- dom-particle had an extra level of batching-asynchrony (a double-debounce which developed after confusion about the first bullet), this is just wasting cycles.
- dom-particle was re-marshaling handle-data that was already provided discretely by onHandleSync/Update, wasting cycles and PEC-trips.
- interface between dom-particle handles and Xen props had become crufty 

Fallout ensuing:
- multiplexer-dom-particle was making assumptions about timing that didn't hold after changes, I had to rearrange some of the logic.

Fixes #2945

### CODE REVIEW

File: src/planning/plan/replan-queue.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ import {now} from '../../platform/date-web.js';
 import {PlanProducer, Trigger} from './plan-producer.js';
 import {Dictionary} from '../../runtime/hot.js';
 
-const defaultDefaultReplanDelayMs = 3000;
+const defaultDefaultReplanDelayMs = 300;
```
Comment (shaper) [inline src/planning/plan/replan-queue.ts]: Double-default naming seems strange but I realize it was already this way.

Comment (sjmiles) [reply src/planning/plan/replan-queue.ts]: Lol, I didn't even notice that. Is it on purpose @mmandlis?

Comment (mmandlis) [reply src/planning/plan/replan-queue.ts]: no, this is by mistake, sorry.

Comment (sjmiles) [reply src/planning/plan/replan-queue.ts]: I can see how it's the `default` for `options.defaultReplanDelayMs`. Maybe the problem is that it should be `options.replayDelayMs`? Is there ever a time where it does something other than the _default_?

Comment (sjmiles) [reply src/planning/plan/replan-queue.ts]: I guess `nextReplanDelayMs` is calculated (so the answer to my question is _yes_). I'm going to tweak the names anyway to remove one 'default'.

Comment (mmandlis) [reply src/planning/plan/replan-queue.ts]: oh, i see it now, sorry for the bad answer as well as poor naming :(
it never does anything other than default, but i wanted it to have to option to...

Comment (sjmiles) [reply src/planning/plan/replan-queue.ts]: Lol, stop worrying so much! Frankly I think your naming was actually precise. I just made it less precise but hopefully more readable. There's no obvious right answer IMO.
