### PR TITLE
Don't fail linking files in case of racing builds

### LINKED ISSUE #4465: Don't fail linking files at racing sigh builds
Current sigh build links src/... to build/... by checking symbolic link existence and file stats under build/... first then creating a symbolic link accordingly.

Travis triggers multiple build targets that executes 'tools/sigh build' concurrently
which may cause racing condition where multiple build tasks are racing to create the symbolic links turns out EEXIST exceptions raised at some of these build tasks.

We need to consider such condition by warning users rather than failing build tasks immediately.

### PR DESCRIPTION
**Pull request by ianull**
Seems this happens more frequently than I thought (multiple/lots of times a day...)
i.e. the recent failure
https://travis-ci.org/PolymerLabs/arcs/jobs/638042883

Create the PR to save work time, otherwise devs need to restart their Travis build/test upon link errors.

Fixed #4465

### CODE REVIEW

File: tools/sigh.ts [hunk 1]
```diff
@@ -415,8 +415,11 @@ function makeLink(src: string, dest: string): boolean {
     }
     fs.linkSync(src, dest);
   } catch (lerr) {
-    console.error(`Error linking ${src} to ${dest} ${lerr.message}`);
-    return false;
+    // In case of racing builds.
+    if (!lerr.message.startsWith('EEXIST:')) {
```
Comment (shaper) [inline tools/sigh.ts]: Thanks for this, two thoughts:
1. Can you file a GH issue to track this so we don't forget?
2. We should probably still log the error even if it's 'EEXIST', but perhaps with a different log level (`warn`?).

Comment (ianull) [reply tools/sigh.ts]: Sure thing.
I'll file an issue when I get up (it's 2am at my time).

Comment (ianull) [reply tools/sigh.ts]: done :-)

**Comment by shaper** [comment]
I had a thought -- are we confident it's a race, or is it possible the Docker + Travis cache is somehow placing/keeping old build files around?

I ask because this could also produce EXISTS error, but in this case we can't rely on the fact that the files as built are still accurate.

We could hash-compare them before considering it a safe failure. I could be overthinking/paranoid but wanted to mention since we are unsure of the caching setup/details overall.

**Comment by shaper** [comment]
My concern above is probably invalid since as you describe in #4465 it's symlinks.

File: tools/sigh.ts [hunk 2]
```diff
@@ -415,8 +415,13 @@ function makeLink(src: string, dest: string): boolean {
     }
     fs.linkSync(src, dest);
   } catch (lerr) {
-    console.error(`Error linking ${src} to ${dest} ${lerr.message}`);
-    return false;
+    // In case of racing builds.
+    if (lerr.message.startsWith('EEXIST:')) {
+      console.warn(`Warn linking ${src} to ${dest} ${lerr.message}`);
```
Comment (csilvestrini) [inline tools/sigh.ts]: Minor nit: `Warning when linking ${src} to ${dest}: ${lerr.message}`
