### PR TITLE
cloud-handles fixes

### LINKED ISSUE #1657: Data Streams Crossed
Sometimes I have observed an error that describes an attempt to assign a field from one Type into a mismatched Type. 

I captured one case [here](https://polymerlabs.github.io/arcs-live/shell/apps/web/?arc=-LHZY2OW5cVwd9VMKPKS&user=-L8ZV2_gCxnL4SSz-16-).

In this case, it looks like it's trying to copy a PlaidAccount into a PlaidTransaction.

The message I see is:

```
storage-proxy.js:476 Error dispatching to particle Error: Can't set field balanceAvailable; not in schema PlaidTransaction
    at validateFieldAndTypes (schema.js:189)
    at Object.set (schema.js:254)
    at new PlaidTransaction (schema.js:261)
    at restore (handle.js:25)
    at Variable._restore (handle.js:230)
    at Variable._notify (handle.js:201)
    at StorageProxyScheduler._dispatch (storage-proxy.js:473)
    at setTimeout (storage-proxy.js:460)
```

### LINKED ISSUE #1680: Gift shopping demo - Chooser particle doesn't render
"Add items from Claire's wishlist" (ie Chooser particle) doesn't render, when the suggestion is accepted.
However, it does render on "refresh"

### PR DESCRIPTION
**Pull request by sjmiles**
Fixes #1680:
- If FB reports a null Variable, only write it locally if there is also metadata (meaning it's been written to FB at least once).

Fixes #1657:
- add type-specificity to cloud-handles generated ids, to avoid remote-handle collisions

**Note that changes to ids will prevent existing Arcs from reading old values.**

Also added some exception plumbing to surface errors in the outer-pec.

### CODE REVIEW

File: runtime/arc-exceptions.js [hunk 1]
```diff
@@ -25,3 +25,8 @@ export function removeSystemExceptionHandler(handler) {
   if (idx > -1)
     systemHandlers.splice(idx, 1);
 }
+
+registerSystemExceptionHandler((exception, methodName, particle) => {
```
Comment (mmandlis) [inline runtime/arc-exceptions.js]: is this needed? i don't see it being used.

Comment (sjmiles) [reply runtime/arc-exceptions.js]: @shans knows more. I believe this is used indirectly, and attaches to the outer-pec side of `proxy.raiseSystemException` (https://github.com/PolymerLabs/arcs/pull/1687/files#diff-1c7794edf33324cf4bd9b510b9e661b5R476).

Comment (shans) [reply runtime/arc-exceptions.js]: It registers an exception handler for system exceptions. Would be used only when system exceptions are generated inside the PEC
